server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/construction_project_sql?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Mysql0918#
  jackson:
    date-format: yyyy-MM-dd
    #joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
log:
  level:
    root: error
    my: info
  file: logs/admin-server.log
  maxsize: 30MB
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #打映输出日志
      #mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
    # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.construction.model