server:
  port: 8765
#spring:
#  security:
#    user:
#      name: mos
#      password: 1234
spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:13306/mybatisplus
      username: root
      password: 1234
