server:
  port: 9099
  servlet:
#   项目访问路径
#    context-path: /thymeleaf
    context-path: /templates

spring:
  #  thymeleaf:
  # 模板路径前缀修改 --默认是  /templates/
  #    prefix: classpath:/thymeleaf/


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/mybatisplus
    username: root
    password: 1234
  application:
#    name: thymeleaf
    name: templates
#  #    热部署
#  devtools:
#    restart:
#      enabled: true