server:
  port: 8989
  servlet:
    # 项目访问路径
#    context-path: /thymeleaf

spring:
#  thymeleaf:
    # 模板路径前缀修改 --默认是  /templates/
#    prefix: classpath:/thymeleaf/


  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Drive
      url: jdbc:mysql://localhost:13306/mybatisplus
      username: root
      password: 1234
  application:
    name: thymeleaf
#    热部署
  devtools:
      restart:
        enabled: true